module.exports = {
  valid: {
    strings: "# Vela quam ius nec\n## Albis mea requiescere si in viro Pyrrhus\n\nLorem markdownum, inconcessisque nullique conplexa in silvae. Vix enim ego quia,\nhabitasse **mane cupidine**, Pyraethi. Neque nam vigor ne oculi\n[matutinaeque](http://imgur.com/): socero ubi deo. Numen maestaeque, pone\n[marmoris remittas tempus](http://gifctrl.com/): o quod spumisque, nil radice\nsine.\n\n- Vetus discussit aprorum ille illam Macareus scindunt\n- Orbem vela quam rogantis tulit\n- Vultus rediret atro surgunt docuique\n- Aperta ait fugit suspiria agmina magni alta\n- Negate pudor fissa nidor Actaea alimentaque\n- Ignes ut augur litusque duraeque unum neque\n\n## Et patrio ut anni\n\nAnaxarete data: erit qua tendebat precor pugnavique mirata. Rupta vaga sed\nmeruisse pars duorum Erigonen: crus sub reverentia Persea forma luce iusta,\nseptem faciem! Deplanxere quis pennas religarat, illa gemunt. Arces nati\nfidissime futura? Sui tamen spreta auro vincemus ordine feret ad in comae\ngenuumque illis!\n\nLoci et aera pecoris maximus; quam fertur! Sedesque monstrare sacraque turbam;\n[pavidum](http://html9responsiveboilerstrapjs.com/) matre, non huic.\n\n## Substravit concorditer valuissent tutior criminis Cerastae\n\nGermana ignes ora **semina retinere absitque** tepidisque sum in miserabilis.\nCoeunt atque. Relictus intrare liliaque, dixit **senior supprimit** legitima\n[eruerit](http://seenly.com/) est anxia traxerunt Tritonida. Et **vidisse\nsigna** cinctasque dixit proterit fulget succrescere haec audax cum verbis\ngenus.\n\n## Portus puerum caperet illiusque at pugnant visis\n\nLoqui hostibus dum soporem semina multaeque videbitur illa narrarent adstat\ndissimilem contraxit bubo: priori. O et tibi sermone. *Ferunt argentea* medium\nper sceleri indignante *secundi*! *Tibi culpa* formam libens: nymphae soli hic\npulsa pueroque quorum, inpellit ego. Lata gratia somno, *et ambarum cognovit*\neminus retentis et modo secedere.\n\n## Athon pennis vesica parientibus victa confugit equos\n\nEcho adspexit brumalis. Ubi est aegre et gerit condidit, acri dixerat?\n\nIta ramos ferenda praesentem adpositi veribus. Hunc vox novorum superata\nconcipit [velle requiescit mensis](http://zeus.ugent.be/). Per ramus suos\nOriente, terrae, Pylio curaque.\n\n[eruerit]: http://seenly.com/\n[marmoris remittas tempus]: http://gifctrl.com/\n[matutinaeque]: http://imgur.com/\n[pavidum]: http://html9responsiveboilerstrapjs.com/\n[velle requiescit mensis]: http://zeus.ugent.be/",
    expected: [ "http://imgur.com/", "http://gifctrl.com/", "http://html9responsiveboilerstrapjs.com/", "http://seenly.com/", "http://zeus.ugent.be/"]
  },
  invalid: {
    strings: "# There's nothing here! [no] (links) (at)[all]!"
  }
};
